"""Add xp column to users

Revision ID: 7db9c1e6d367
Revises: 
Create Date: 2026-05-23 01:20:31.817032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db9c1e6d367'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_user_quests_id'), table_name='user_quests')
    op.drop_table('user_quests')
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    op.drop_column('users', 'exp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'xp')
    op.create_table('user_quests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('user_quests_quest_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_quests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_quests_pkey'))
    )
    op.create_index(op.f('ix_user_quests_id'), 'user_quests', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intelligence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discipline', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skills_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    # ### end Alembic commands ###
